global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          site: 'prod'

  - job_name: 'mysql'
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['172.28.0.70:9104']
        labels:
          site: 'prod'

  - job_name: 'nginx_status'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']    
        labels:
          site: 'prod'

  - job_name: 'blackbox-http_2xx'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx] # наш модуль из blackbox.yml
    static_configs:
      - targets:
        - http://172.28.0.10 # что мониторим
        labels:
          site: 'prod'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # адрес сервиса blackbox

  - job_name: 'SSL-blackbox-http_2xx'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx] # наш модуль из blackbox.yml
    static_configs:
      - targets:
        - https://172.28.0.10 # что мониторим
        labels:
          site: 'prod'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # адрес сервиса blackbox      

